src/main/java/eu/boss/mobilesport/jsf/beans/AgendaBean.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import eu.boss.mobilesport.exceptions.BossException;
import eu.boss.mobilesport.fff.FFFWeb;

@ManagedBean
@RequestScoped
public class AgendaBean implements Serializable {

	private static final long serialVersionUID = -6487985440925721694L;
	private static final Logger LOGGER = Logger.getLogger(AgendaBean.class.getName());

	private String htmlAgenda;

	public String getHtmlAgenda() {
		try {
			LOGGER.info("Loading agenda");
			if (htmlAgenda == null) htmlAgenda = FFFWeb.loadAgenda(false);
		} catch (BossException e) {
			htmlAgenda = "<p>Erreur de chargement de la page. Veuillez réessayer</p>";
			LOGGER.severe(e.getMessage());
		}
		return htmlAgenda;
	}

	public void setHtmlAgenda(String htmlAgenda) {
		this.htmlAgenda = htmlAgenda;
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/CalendarBean.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import eu.boss.mobilesport.datastore.TeamsManager;
import eu.boss.mobilesport.exceptions.BossException;
import eu.boss.mobilesport.fff.FFFWeb;
import eu.boss.mobilesport.model.Team;
import eu.boss.mobilesport.utils.Util;

@ManagedBean
@ViewScoped
public class CalendarBean implements Serializable {

	private static final long serialVersionUID = -6487985440925721694L;
	private static final Logger LOGGER = Logger.getLogger(CalendarBean.class.getName());

	private String htmlCalendar;

	private String teamCat;
	private String teamName;

	private List<String> seasons = Util.getSeasonsList();
	private String selectedSeason = Util.currentSeasonDate();

	@PostConstruct
	public void init() {
		LOGGER.info("Loading calendar");
		Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext()
				.getRequestParameterMap();
		if (params != null) {
			teamCat = params.get("category");
			teamName = params.get("team");
		}
		loadCalendar();

	}

	public void loadCalendar() {
		try {
			Team t = TeamsManager.loadTeamForSeason(teamCat, teamName, selectedSeason);
			String url = t.getUrlCalendar();
			htmlCalendar = FFFWeb.loadCalendarFromUrl(url, false);
		} catch (BossException e) {
			e.printStackTrace();
			LOGGER.severe(e.getMessage());
		}
	}

	public String getHtmlCalendar() {
		return htmlCalendar;
	}

	public void setHtmlCalendar(String htmlCalendar) {
		this.htmlCalendar = htmlCalendar;
	}

	public String getTeamCat() {
		return teamCat;
	}

	public void setTeamCat(String teamCat) {
		this.teamCat = teamCat;
	}

	public String getTeamName() {
		return teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public List<String> getSeasons() {
		return seasons;
	}

	public void setSeasons(List<String> seasons) {
		this.seasons = seasons;
	}

	public String getSelectedSeason() {
		return selectedSeason;
	}

	public void setSelectedSeason(String selectedSeason) {
		this.selectedSeason = selectedSeason;
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/CanvasFormationItem.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;

import eu.boss.mobilesport.externalmodel.FormationItemMessage;

public class CanvasFormationItem implements Serializable, Comparable<CanvasFormationItem> {

	private static final long serialVersionUID = -3034501531215196425L;
	private String strIdx;
	private FormationItemMessage formationItem;

	public String getStrIdx() {
		return strIdx;
	}

	public void setStrIdx(String strIdx) {
		this.strIdx = strIdx;
	}

	public FormationItemMessage getFormationItem() {
		return formationItem;
	}

	public void setFormationItem(FormationItemMessage formationItem) {
		this.formationItem = formationItem;
	}

	@Override
	public int compareTo(CanvasFormationItem formationItemToCompare) {

		if (formationItem == null || formationItem.getNumItem() == null) return 1;
		else if (formationItemToCompare == null || formationItemToCompare.getFormationItem() == null) return 0;
		else if (formationItem.getNumItem() < formationItemToCompare.getFormationItem().getNumItem()) return 1;
		else return 0;
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/ContactBean.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;
import java.util.Properties;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import eu.boss.mobilesport.utils.Constant;
import eu.boss.mobilesport.utils.EnumProperties;
import eu.boss.mobilesport.utils.Prop;

@ManagedBean
public class ContactBean implements Serializable {

	private static final long serialVersionUID = -6487985440925721694L;
	private static final Logger LOGGER = Logger.getLogger(ContactBean.class.getName());

	private String contactMail;
	private String contactName;
	private String message;

	public String submit() {
		try {
			LOGGER.info("Submit contact form");
			sendEmail();

			return "contactFormSent?faces-redirect=true";
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.severe(e.getMessage());
			return "failed";
		}
	}

	public void sendEmail() {
		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props, new javax.mail.Authenticator() {

			@Override
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(Constant.CONTACT_EMAIL, Constant.GENERIC_PWD);
			}
		});

		try {
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(Constant.CONTACT_EMAIL, contactName));
			message.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(Constant.CONTACT_RECIPIENT));
			message.setSubject("Contact "
					+ Prop.getInstance(EnumProperties.LABELS).getString("header.teamName"));
			message.setText("Adresse de contact: " + contactMail + "\n\n" + this.message);

			Transport.send(message);

			LOGGER.info("Email sent");

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public String getContactMail() {
		return contactMail;
	}

	public void setContactMail(String contactMail) {
		this.contactMail = contactMail;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/Document.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;

public class Document implements Serializable, Comparable<Document> {

	private static final long serialVersionUID = 4845322621896305733L;

	private String name;

	private DocumentType type;

	public Document(String name, DocumentType type) {
		this.name = name;
		this.type = type;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public DocumentType getType() {
		return type;
	}

	public void setType(DocumentType type) {
		this.type = type;
	}

	// Eclipse Generated hashCode and equals
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Document other = (Document) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return name;
	}

	public int compareTo(Document document) {
		return this.getName().compareTo(document.getName());
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/DocumentType.java
package eu.boss.mobilesport.jsf.beans;

public enum DocumentType {
	FOLDER, PICTURE;
}

src/main/java/eu/boss/mobilesport/jsf/beans/LiveDetailsBean.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import eu.boss.mobilesport.datastore.LiveManager;
import eu.boss.mobilesport.model.Comment;
import eu.boss.mobilesport.model.Match;

@ManagedBean
@ViewScoped
public class LiveDetailsBean implements Serializable {

	private static final long serialVersionUID = -7302019881196721706L;
	private Match match;
	private List<Comment> comments;

	@PostConstruct
	private void initIfEditing() {
		Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext()
				.getRequestParameterMap();
		Long matchId = null;
		if (params.get("id") != null) matchId = Long.valueOf(params.get("id"));

		if (matchId != null) {
			this.match = LiveManager.getMatchById(matchId);
			this.comments = LiveManager.getCommentsForMatch(matchId);
		}

	}

	public Match getMatch() {
		return match;
	}

	public void setMatch(Match match) {
		this.match = match;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

}

src/main/java/eu/boss/mobilesport/jsf/beans/NewsManagerBean.java
package eu.boss.mobilesport.jsf.beans;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.Map;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.el.ELContext;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

import eu.boss.mobilesport.datastore.CloudServiceManager;
import eu.boss.mobilesport.datastore.NewsManager;
import eu.boss.mobilesport.externalmodel.NewsType;
import eu.boss.mobilesport.model.News;
import eu.boss.mobilesport.pushnotifications.NotificationType;
import eu.boss.mobilesport.pushnotifications.PushNotificationManager;
import eu.boss.mobilesport.utils.Constant;

@ManagedBean
@ViewScoped
/**
 * Initialization of blobstore url. Used to upload file on the cloud
 * 
 * @author Arnaud
 */
public class NewsManagerBean implements Serializable {

	private static final long serialVersionUID = 3271496816208332663L;
	private static final Logger LOGGER = Logger.getLogger(NewsManagerBean.class.getName());

	private String title;
	private String text;
	private String newsType = NewsType.AUTRE.getLabel();
	private boolean sendNotification;
	private boolean displayImageSelection = true;
	private boolean editing = false;
	private boolean keepOldImage;
	private UploadedFile uploadedImage;
	private News newsToEdit;

	/**
	 * On check s'il y a des parametres passes. S'il y en a, on recupere la news associee pour
	 * l'editer ou le match dont on veut automatiser la convocation
	 */
	@PostConstruct
	private void init() {
		Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext()
				.getRequestParameterMap();
		String edit = params.get("edit");
		Long newsId = null;

		if (params.get("id") != null) newsId = Long.valueOf(params.get("id"));

		if (params.get("generateConvoc") != null && params.get("generateConvoc").equals("y")) {
			// On va recuperer le match dans le bean temporaire
			ELContext elContext = FacesContext.getCurrentInstance().getELContext();
			TempMatchCreationBean tempMatchBean = (TempMatchCreationBean) elContext.getELResolver()
					.getValue(elContext, null, "tempMatchCreationBean");

			// On recupere le match et la formation stockes dans le bean
			// temporaire

			setNewsType(NewsType.CONVOCATION.getLabel());
			this.title = tempMatchBean.getMatch().getConvocTitle();
			this.text = tempMatchBean.getMatch().getConvocContent()
					+ "******* VEUILLEZ PRECISER L'HEURE DE RENDEZ-VOUS *******" + "<div><br></div>"
					+ tempMatchBean.getFormation().getConvocs();
		}

		if ((edit != null) && (edit.equals("true")) && (newsId != null)) {
			editing = true;
			this.newsToEdit = NewsManager.getNewsById(newsId);
			this.title = newsToEdit.getTitle();
			this.text = newsToEdit.getContent();
			this.keepOldImage = true;
		}
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getNewsType() {
		return newsType;
	}

	public void setNewsType(String newsType) {

		if (newsType.equals(NewsType.AUTRE.name())) displayImageSelection = true;
		else displayImageSelection = false;

		this.newsType = newsType;
	}

	public boolean getDisplayImageSelection() {
		return displayImageSelection;
	}

	public void setDisplayImageSelection(boolean displayImageSelection) {
		this.displayImageSelection = displayImageSelection;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String addNews() throws UnsupportedEncodingException {
		try {
			// FIX: Primefaces bug, see
			// http://stackoverflow.com/questions/11190081/primefaces-fileupload-filter-with-utf8-characters-filter
			this.text = new String(text.getBytes("ISO-8859-1"), "UTF-8");
			this.title = new String(title.getBytes("ISO-8859-1"), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			LOGGER.severe("error encoding utf8: " + e.toString());
		}

		LOGGER.info("addNews: " + title);
		LOGGER.info("displayImageSelection: " + displayImageSelection);
		LOGGER.info("keepOldImage: " + keepOldImage);
		String imageUrl = "";
		String newsTypeBis = newsType;

		if (newsType.equals(NewsType.AGENDA.name())) imageUrl = Constant.AGENDA_IMG_URL;
		else if (newsType.equals(NewsType.RESULTAT.name())) imageUrl = Constant.RESULTS_IMG_URL;
		else if (newsType.equals(NewsType.CONVOCATION.name())) imageUrl = Constant.CONVOCS_IMG_URL;

		else if (!keepOldImage && newsType.equals(NewsType.AUTRE.name())) {
			try {
				imageUrl = uploadSelectedImage();
			} catch (Exception e) {
				LOGGER.severe("Exception saving news: " + e.toString());
				return "error";
			}
		} else {
			// On est en mode edition et on garde l'ancienne image
			imageUrl = newsToEdit.getImageUrl();
			newsTypeBis = newsToEdit.getNewsType().getLabel();
		}

		if (editing) {
			newsToEdit.setTitle(title);
			newsToEdit.setContent(text);
			newsToEdit.setImageUrl(imageUrl);
			newsToEdit.setNewsType(NewsType.getByLabel(newsTypeBis));
			NewsManager.editNews(newsToEdit);
			return "newsedited";
		} else {
			News news = new News(title, new Date(), imageUrl, "", text, NewsType.valueOf(newsType));
			if (NewsManager.addNews(news) == null) {
				LOGGER.severe("Error saving news");
				return "error";
			}
			if (sendNotification) {
				if (!PushNotificationManager.sendNotificationMsgToAll(title, text,
						NotificationType.NEWS, imageUrl, "" + news.getId()))
					LOGGER.severe("Problem sending push notification");
			}
			return "newsadded";
		}

	}

	public void handleFileUpload(FileUploadEvent event) {
		LOGGER.info("handleFileUpload: " + event.getFile().getFileName());
		this.uploadedImage = event.getFile();
	}

	private String uploadSelectedImage() throws Exception {
		try {
			String filename = CloudServiceManager.uploadImageFile(uploadedImage.getInputstream(),
					uploadedImage.getContentType(), uploadedImage.getFileName(), Constant.FOLDER_NEWS);

			LOGGER.info(uploadedImage.getFileName() + " a été importé avec succès.");
			return filename;
		} catch (Exception e) {
			LOGGER.severe("Problem uploading image: " + e.toString());
			throw e;
		}
	}

	public String getFileName() {
		if (this.uploadedImage != null && this.uploadedImage.getFileName() != null)
			return this.uploadedImage.getFileName();
		return "";
	}

	public boolean getSendNotification() {
		return sendNotification;
	}

	public void setSendNotification(boolean sendNotification) {
		this.sendNotification = sendNotification;
	}

	public boolean isEditing() {
		return editing;
	}

	public void setEditing(boolean isEditing) {
		this.editing = isEditing;
	}

	public boolean isKeepOldImage() {
		return keepOldImage;
	}

	public void setKeepOldImage(boolean keepOldImage) {
		this.keepOldImage = keepOldImage;
	}

	public UploadedFile getUploadedImage() {
		return uploadedImage;
	}

	public void setUploadedImage(UploadedFile uploadedImage) {
		this.uploadedImage = uploadedImage;
	}

}

src/main/webapp/calendar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />
	</f:facet>
	<title>#{labels['calendar.page.title']}</title>
	<link type="text/css" rel="stylesheet" href="/static/style.css" />
</h:head>

<h:body>

	<p:layout fullPage="true">
		<p:layoutUnit position="north" size="110" id="north" resizable="false">
			<ui:include src="templates/header.xhtml" />
		</p:layoutUnit>

		<p:layoutUnit position="west" id="west" resizable="false" size="250">
			<ui:include src="templates/menu.xhtml" />
		</p:layoutUnit>

		<p:layoutUnit styleClass="layoutUnitCenter" position="center"
			style="padding: 0.4% 2%;">

			<h:form>

				<h:selectOneMenu id="selectSeason"
					value="#{calendarBean.selectedSeason}"
					style="float:right; margin-top:10px !important">
					<f:selectItems value="#{calendarBean.seasons}" var="season"
						itemLabel="#{season}" itemValue="#{season}" />

					<p:ajax onsuccess=" PF('statusDialog').hide()" update="calendar"
						onstart="PF('statusDialog').show();"
						listener="#{calendarBean.loadCalendar}" />
				</h:selectOneMenu>

				<h:outputLabel
					style="float:right;margin-right:5px; margin-top:10px !important">#{labels['generic.season']}</h:outputLabel>

				<h:outputText id="calendar" escape="false"
					value="#{calendarBean.htmlCalendar}" />

			</h:form>

			<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
				closable="false" resizable="false" showHeader="false">
				<img src="/static/loading.gif" alt="Logo" class="loadingDialog" />
				<p:outputLabel value="#{labels['stats.message.processing']}"></p:outputLabel>
			</p:dialog>

		</p:layoutUnit>
	</p:layout>

</h:body>


</html>

src/main/webapp/newsManager.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	

<h:head>
	<f:facet name="first">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />
	</f:facet>
	<title>#{labels['newsMng.page.title']}</title>
	<link type="text/css" rel="stylesheet" href="/static/style.css" />
	<style media="screen" type="text/css">
.ui-fileupload-buttonbar {
	background: transparent !important;
	border: none;
}

.ui-fileupload-content {
	border: none;
}

.ui-fileupload {
	display: inline-block !important;
}
</style>
	<script>
		$(function() {
			$(".ui-editor-group>.ui-editor-button").each(function() {
				var title = $(this).attr("title").toLowerCase();
				switch (title) {
				case "bold":
					title = "Gras";
					break;
				case "italic":
					title = "Italique";
					break;
				case "underline":
					title = "Souligné";
					break;
				case "strikethrough":
					title = "Barré";
					break;
				case "font size":
					title = "Taille de la police";
					break;
				case "style":
					title = "Style";
					break;
				case "font":
					title = "Police";
					break;
				case "font color":
					title = "Couleur texte";
					break;
				case "align text left":
					title = "Aligner texte à gauche";
					break;
				case "center":
					title = "Centrer";
					break;
				case "align text right":
					title = "Aligner texte à droite";
					break;
				case "justify":
					title = "Justifier";
					break;

				}
				$(this).attr("title", title);
			})
		})
	</script>
</h:head>

<h:body>
	<p:layout fullPage="true">
		<p:layoutUnit position="north" size="110" id="north" resizable="false">
			<ui:include src="templates/header.xhtml" />
		</p:layoutUnit>

		<p:layoutUnit position="west" id="west" resizable="false" size="250">
			<ui:include src="templates/menu.xhtml" />
		</p:layoutUnit>

		<p:layoutUnit styleClass="layoutUnitCenter" position="center"
			rendered="#{loginBean.isLogged}" style="padding: 0.4% 2%;">
			<h:panelGroup rendered="#{!newsManagerBean.editing}">
				<h2>#{labels['newsMng.title.new']}</h2>
			</h:panelGroup>
			<h:panelGroup rendered="#{newsManagerBean.editing}">
				<h2>#{labels['newsMng.title.edit']}</h2>
			</h:panelGroup>

			<p>
				<i>#{labels['newsMng.legend.details']}</i>
			</p>

			<h:form enctype="multipart/form-data" >
				<p:messages id="messages" autoUpdate="true" closable="true" />
				<br />
				<h:outputLabel for="newsType" value="#{labels['newsMng.newsType']}" />
				<h:selectOneMenu id="newsType" value="#{newsManagerBean.newsType}"
					style="margin-left:10px" required="true" label="Type de News">
					<f:selectItem itemLabel="#{labels['newsMng.newsType.other']}"
						itemValue="#{labels['newsMng.newsType.otherValue']}" />
					<f:selectItem itemLabel="#{labels['newsMng.newsType.agenda']}"
						itemValue="#{labels['newsMng.newsType.agendaValue']}" />
					<f:selectItem
						itemLabel="#{labels['newsMng.newsType.convocations']}"
						itemValue="#{labels['newsMng.newsType.convocationsValue']}" />
					<f:selectItem itemLabel="#{labels['newsMng.newsType.results']}"
						itemValue="#{labels['newsMng.newsType.resultsValue']}" />
					<p:ajax event="change" update="pnlImageSelection" />
				</h:selectOneMenu>

				<br />
				<br />
				<p:outputLabel for="title" value="#{labels['newsMng.news.title']}"
					style="display:none" />
				<p:inputText type="text" name="title" id="title"
					placeholder="#{labels['newsMng.news.title']}" style="width:250px;"
					maxlength="50" value="#{newsManagerBean.title}" required="true" />
				<br />
				<br />
				<p:outputLabel for="editor"
					value="#{labels['newsMng.news.content']}" style="display:none" />
				<p:editor placeholder="#{labels['newsMng.news.content']}"
					id="editor" language="fr" required="true"
					controls="bold italic underline strikethrough font size style color alignleft center alignright justify link"
					widgetVar="editorWidget" value="#{newsManagerBean.text}"
					width="600"
					onchange="document.getElementById('content').value = 'this.value'" />
				<br />

				<h:panelGroup id="pnlImageSelection">
					<h:panelGrid columns="1"
						rendered="#{newsManagerBean.displayImageSelection}">
						<h4>#{labels['newsMng.news.image']}</h4>

						<h:panelGrid columns="2" style="margin-bottom:10px"
							cellpadding="5" rendered="#{newsManagerBean.editing}">
							<h:outputText value="#{labels['newsMng.news.keepImg']}" />
							<p:selectBooleanCheckbox value="#{newsManagerBean.keepOldImage}"
								name="keepOldImage">
								<p:ajax event="change" update="pnlImageSelection" />
							</p:selectBooleanCheckbox>
						</h:panelGrid>

						<h:panelGroup rendered="#{!newsManagerBean.keepOldImage}">

							<p:fileUpload
								fileUploadListener="#{newsManagerBean.handleFileUpload}"
								auto="true" dragDropSupport="false"
								sizeLimit="1050000"
								invalidSizeMessage="#{labels['newsMng.news.imagetoobig']}"
								invalidFileMessage="#{labels['newsMng.news.wrongfile']}"
								mode="advanced" update="messages, filename"
								label="Choisir image" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
							<p:outputLabel id="filename" value="#{newsManagerBean.fileName}"></p:outputLabel>
						</h:panelGroup>
					</h:panelGrid>
				</h:panelGroup>
				<br />
				<br />

				<h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5"
					rendered="#{!newsManagerBean.editing}">
					<h:outputText value="#{labels['newsMng.news.sendNotif']}" />
					<p:selectBooleanCheckbox
						value="#{newsManagerBean.sendNotification}" name="notification" />
				</h:panelGrid>

				<p:commandButton value="#{labels['generic.btn.validate']}"
					ajax="false" type="submit" onsuccess="PF('statusDialog').hide()"
					onclick="PF('statusDialog').show();" process="@form"
					action="#{newsManagerBean.addNews}" />

				<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
					closable="false" resizable="false" showHeader="false">
					<img src="/static/loading.gif" alt="Logo" class="loadingDialog" />
					<p:outputLabel value="#{labels['stats.message.processing']}"></p:outputLabel>
				</p:dialog>

			</h:form>
		</p:layoutUnit>

		<p:layoutUnit styleClass="layoutUnitCenter" position="center"
			rendered="#{!loginBean.isLogged}" style="padding: 0.4% 2%;">
			<h:outputText value="#{labels['generic.error.403']}" />
		</p:layoutUnit>
	</p:layout>
</h:body>

</html>